import Head from 'next/head';

import axios from 'axios';

import { useState, FormEvent } from 'react';

import Link from 'next/link';

import { useRouter } from 'next/router';

import { InputGroup } from '../components/inputGroup';

export default function Register() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [username, setUsername] = useState('');
	const [agreement, setAgreement] = useState(false);
	const [errors, setErrors] = useState<any>({});

	const router = useRouter();

	const submitForm = async (e: FormEvent) => {
		e.preventDefault();

		if (!agreement) {
			setErrors({ ...errors, agreement: `You must agree to T&C's` });
			return;
		}

		try {
			await axios.post('/auth/register', {
				email,
				password,
				username,
			});
			router.push('/login');
		} catch (err) {
			setErrors(err.response.data);
		}
	};

	if (!agreement) {
		console.log(errors);
	}

	return (
		<div className='flex'>
			<Head>
				<title>Register</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div
				className='h-screen bg-white bg-center bg-cover w-36'
				style={{
					backgroundImage: "url('./images/tiles.jpg')",
				}}
			></div>
			<div className='flex flex-col justify-center pl-6'>
				<div className='w-70'>
					<h1 className='mb-2 text-lg'>Sign Up</h1>
					<p className='mb-10 text-xs'>
						By continuing you agree to our User Agreement and Privacy Policy.
					</p>
					<form onSubmit={submitForm}>
						<div className='mb-6'>
							<input
								className='mr-1 cursor-pointer'
								type='checkbox'
								id='agreement'
								checked={agreement}
								onChange={(e) => setAgreement(e.target.checked)}
							/>
							<label htmlFor='agreement' className='text-xs cursor-pointer'>
								I agree to get emails about cool stuff on Readit
							</label>
							<small className='block font-medium text-red-600'>
								{errors.agreement}
							</small>
						</div>
						<InputGroup
							className='mb-2'
							error={errors.email}
							value={email}
							setValue={setEmail}
							type='email'
							name='email'
							inputId='email'
							placeholder='email'
						/>
						<InputGroup
							className='mb-2'
							error={errors.username}
							value={username}
							setValue={setUsername}
							type='username'
							name='username'
							inputId='username'
							placeholder='username'
						/>
						<InputGroup
							className='mb-2'
							error={errors.password}
							value={password}
							setValue={setPassword}
							type='password'
							name='password'
							inputId='password'
							placeholder='password'
						/>
						<button className='w-full py-2 mb-4 text-xs font-bold text-white uppercase bg-blue-500 border-blue-500 rounded'>
							Sign up
						</button>
					</form>
					<small>
						Already a readitor?
						<Link href='/login'>
							<a className='ml-1 text-blue-500 uppercase'>Log In</a>
						</Link>
					</small>
				</div>
			</div>
		</div>
	);
}
